version: '3'
services:
  # redis
  redis:
    image: sonatype/nexus3:latest
    container_name: nexus3
    privileged: true  # 授权
    ports:
      - 8081:8081
    volumes:
      - /data/nexus-data:/nexus-data